apiVersion: apps/v1
kind: Deployment
metadata:
  name: dharm-eta-deploy1
  labels:
    app: dharm-eta-deploy-lbl1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dharm-eta-app
  template:
    metadata:
      labels:
        app: dharm-eta-app
    spec:
      containers:
      - name: dharm-eta-container
        image: dhiren1810/java:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dharm-eta-np-service1
  labels:
    app: dharm-eta-np-app
spec:
  selector:
    app: dharm-eta-deploy-lbl1

  type: NodePort
  ports:
  - nodePort: 31030
    port: 8080
    targetPort: 8080
