apiVersion: apps/v1
kind: Deployment
metadata:
  name: loksai-eta-deploy1
  labels:
    app: loksai-eta-deploy-lbl1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loksai-eta-app
  template:
    metadata:
      labels:
        app: loksai-eta-app
    spec:
      containers:
      - name: loksai-eta-container
        image: loksaieta/dcp-jan11-appimg:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: loksai-eta-np-service1
  labels:
    app: loksai-eta-np-app
spec:
  selector:
    app: loksai-eta-deploy-lbl1

  type: NodePort
  ports:
  - nodePort: 31030
    port: 8080
    targetPort: 8080
